# Generated by Django 5.2.4 on 2026-01-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0014_favoritedesign'),
        ('payments', '0002_purchase_discount_percent_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('KZT', 'Kazakhstani Tenge'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], max_length=3)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designs.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
