# Generated by Django 5.2.4 on 2025-10-27 16:07

import designs.models
import designs.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_designreview_designrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoopSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('RE36b', 'RE36b (200×360 мм)'), ('RE28b', 'RE28b (200×280 мм)'), ('SQ20b', 'SQ20b (200×200 мм)'), ('RE20b', 'RE20b (140×200 мм)'), ('SQ14b', 'SQ14b (140×140 мм)'), ('RE10b', 'RE10b (100×40 мм)'), ('ASQ18b', 'ASQ18b (184×184 мм)'), ('SQ10e', 'SQ10e (100×100 мм)')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField(help_text='Ширина в мм')),
                ('height', models.IntegerField(help_text='Высота в мм')),
                ('compatible_machines', models.TextField(help_text='Совместимые модели машин')),
            ],
            options={
                'verbose_name': 'Размер пялец',
                'verbose_name_plural': 'Размеры пялец',
            },
        ),
        migrations.AddField(
            model_name='design',
            name='design_height',
            field=models.IntegerField(default=100, help_text='Высота дизайна в мм'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_width',
            field=models.IntegerField(default=100, help_text='Ширина дизайна в мм'),
        ),
        migrations.AddField(
            model_name='design',
            name='compatible_hoops',
            field=models.ManyToManyField(blank=True, help_text='Выберите пяльца, для которых подходит этот дизайн', to='designs.hoopsize', verbose_name='Совместимые пяльца'),
        ),
        migrations.CreateModel(
            name='DesignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_file', models.FileField(storage=designs.models.PlusFriendlyStorage(), upload_to='designs/variants/', validators=[designs.validators.validate_embroidery_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='designs.design')),
                ('hoop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.hoopsize')),
            ],
            options={
                'verbose_name': 'Вариант дизайна',
                'verbose_name_plural': 'Варианты дизайнов',
                'unique_together': {('design', 'hoop')},
            },
        ),
    ]
