# Generated by Django 5.2.4 on 2026-01-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_design_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='design',
            name='price',
        ),
    ]
