# Generated by Django 5.2.7 on 2026-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_remove_design_discount_percent_remove_design_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тип машины',
                'verbose_name_plural': 'Типы машин',
            },
        ),
        migrations.RemoveField(
            model_name='design',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='design',
            name='machine_types',
            field=models.ManyToManyField(blank=True, related_name='designs', to='designs.machinetype'),
        ),
    ]
