# Generated by Django 5.2.7 on 2026-01-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0012_machinetype_remove_design_machine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='designs.category'),
        ),
    ]
