# Generated by Django 5.2.4 on 2026-01-10 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_remove_design_discount_percent_remove_design_price'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='designs.design')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='designs.design')),
            ],
        ),
    ]
