# Generated by Django 5.2.4 on 2025-10-26 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='design',
            name='design_size',
            field=models.CharField(blank=True, default='100x100', help_text='Размер дизайна в мм (например: 100x100)', max_length=100),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=models.FileField(upload_to='designs/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pes', 'dst', 'jef', 'exp', 'jef+'])]),
        ),
    ]
