# Generated by Django 5.2.4 on 2025-10-26 17:51

import designs.models
import designs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_alter_design_design_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=models.FileField(storage=designs.models.PlusFriendlyStorage(), upload_to=designs.models.upload_to_original, validators=[designs.validators.validate_embroidery_file]),
        ),
    ]
