# Generated by Django 5.2.4 on 2025-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_hoopsize_design_design_height_design_design_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='stitch_count',
            field=models.IntegerField(default=0, help_text='Общее количество стежков в дизайне'),
        ),
        migrations.AddField(
            model_name='designvariant',
            name='stitch_count',
            field=models.IntegerField(default=0, help_text='Количество стежков для этого варианта'),
        ),
    ]
