# Generated by Django 5.2.7 on 2025-12-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_design_stitch_count_designvariant_stitch_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
