# Generated by Django 5.2.7 on 2025-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Скидка в процентах'),
        ),
    ]
