# Generated by Django 5.2.7 on 2026-01-10 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0013_alter_design_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='designs.design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный дизайн',
                'verbose_name_plural': 'Избранные дизайны',
                'unique_together': {('user', 'design')},
            },
        ),
    ]
