# Generated by Django 5.2.7 on 2026-04-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0014_favoritedesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designs/gallery/')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.design')),
            ],
        ),
    ]
