# Generated by Django 5.2.7 on 2026-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0015_designimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/gallery/'),
        ),
    ]
